.NOTE man 7 man
.TH OPDIS 1 "February 13, 2010" "" "Development Tools"

.SH NAME
opdis \- program for...

.SH SYNOPSIS
opdis [\fB\-a\fR|\fB\-\-action\fR=\fIjobspec\fR]
      [\fB\-s\fR|\fB\-\-syntax\fR=\fIatt\fR|\fIintel\fR]
      [\fB\-f\fR|\fB\-\-format\fR=\fIfmtspec\fR]
      [\fB\-o\fR|\fB\-\-output\fR=\fIfilename\fR]
      [\fB\-m\fR|\fB\-\-map\fR=\fImapspec\fR]
      [\fB\-b\fR|\fB\-\-bytes\fR=\fIstring\fR]
      [\fB\-B\fR|\fB\-\-bfd\fR[=\fIbfdspec\fR\]
      [\fB\-\-dry\-run\fR]
      \fIobjfile\fR...
.br

.SH DESCRIPTION
This manual page explains the
.B opdis
program. This program...
.PP
\fBopdis\fP is for...

.SH OPTIONS
.IP \fB-a\fR \fIcflow\fR|\fIlinear\fR[\fImemspec\fR]
.PD 0
.IP \fB--action\fR=\fIjobspec\fR
.PD
action...
.PD
See \fBADDRESS FORMAT\fR.
.IP \fB-s\fR \fIatt\fR|\fIintel\fR
.PD 0
.IP \fB--syntax\fR=\fIatt\fR|\fIintel\fR
.PD
syntax..
.IP \fB-F\fR \fIformat_string\fR
.PD 0
.IP \fB--format\fR=\fIformat_string\fR
.PD
output format
.PD
See \fBFORMAT STRINGS\fR.
.IP \fB-o\fR \fIfilename\fR
.PD 0
.IP \fB--output\fR=\fIfilename\fR
.PD
output file
.IP \fB-m\fR \fImemspec\fR
.PD 0
.IP \fB--map\fR=\fImemspec\fR
.PD
map
.PD
See \fBADDRESS FORMAT\fR.
.IP \fB-b\fR \fIstring\fR
.PD 0
.IP \fB--bytes\fR=\fIstring\fR
.PD
target
.IP \fB-B\fR [\fIbfdspec\fR]
.PD 0
.IP \fB--bfd\fR[=\fIbfdspec\fR]
.PD
bfd lib
.IP \fB--dry-run\fR
.PD
do nothing

.IP -OPTION
This option...

.SH ADDRESS FORMAT
	[target]:offset|@vma[+size]

.SH FORMAT STRINGS
printf-style format string for output
.B
Operations
.IP
	\fB%[len]o[l|#]\fR
.PD
operand list or #
.IP
	\fB%b[[0][#]x|X|o|O|d|D|a|A][len]\fR 
.PD
bytes
.IP
	\fB%[len]m\fR
.PD
mnemonic
.IP
	\fB%v\fR
.PD
vma
.IP
	\fB%a\fR 
.PD
address (offset)
.IP
	\fB%f[si]m|o#\fR 
.PD
flags string|int mnemonic|operand#
.IP
	\fB%p\fR
.PD
prefixes
.IP
	\fB%c[delim]\fR
.PD
conditional delimiter
	
.B
Length modifiers
.B
Format modifiers

.SH NOTES

.SH EXAMPLE

.SH "SEE ALSO"

